export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const ORDER_CART = 'ORDER_CART';
